# Generated by Django 4.2.7 on 2024-01-17 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
    ]
