# Generated by Django 4.2.6 on 2023-10-22 13:21

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adopter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shortuuid.main.ShortUUID.uuid, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("owner", models.CharField(max_length=255, verbose_name="Full name of owner")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=9, message="Phone number must have 9 digits."
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Address")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update date")),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, auto_created=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=shortuuid.main.ShortUUID.uuid, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=2, message="Name must be at least 2 characters long."
                            )
                        ],
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(choices=[("DOG", "Dog"), ("CAT", "Cat")], max_length=255, verbose_name="Type"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=50, verbose_name="Gender"
                    ),
                ),
                ("birth_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOR_ADOPTION", "For Adoption"),
                            ("ADOPTED", "Adopted"),
                            ("QUARANTINE", "Quarantine"),
                            ("UNADOPTABLE", "Unadoptable"),
                        ],
                        default="UNADOPTABLE",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                ("location_where_found", models.CharField(max_length=255)),
                ("date_when_found", models.DateField()),
                (
                    "residence",
                    models.CharField(
                        choices=[("BASE", "Base"), ("TEMPORARY_HOME", "Temporary home")],
                        default="BASE",
                        max_length=255,
                    ),
                ),
                ("description_of_health", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="animals/")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update date")),
            ],
        ),
        migrations.CreateModel(
            name="HealthCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shortuuid.main.ShortUUID.uuid, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("allergies", models.JSONField()),
                ("drugs", models.JSONField()),
                ("vaccinations", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update date")),
                (
                    "animal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="healthcards", to="core.animal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryHome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shortuuid.main.ShortUUID.uuid, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("owner", models.CharField(max_length=255, verbose_name="Full name of owner")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=9, message="Phone number must have 9 digits."
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                ("street", models.CharField(max_length=255, verbose_name="Street")),
                ("building", models.CharField(max_length=20, verbose_name="Building number")),
                ("aparment", models.CharField(max_length=10, verbose_name="Apartment number")),
                (
                    "zip_code",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=5, message="Zip code must have 5 digits."
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update date")),
            ],
        ),
        migrations.CreateModel(
            name="VeterinaryVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "doctor",
                    models.CharField(
                        choices=[("PIOTR", "Piotr"), ("JOANNA", "Joanna"), ("ALEKSANDRA", "Aleksandra")],
                        max_length=255,
                        verbose_name="Doctor",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date of visit")),
                ("description", models.TextField(verbose_name="Visit description")),
                (
                    "health_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinaryvisits",
                        to="core.healthcard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="home",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="core.temporaryhome",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="animals", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
