# Generated by Django 4.2.6 on 2023-10-25 18:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("FOOD", "Pokarm"), ("CONTACT", "Kontakt"), ("INHALATION", "Inhalacja")],
                        max_length=255,
                        verbose_name="Allergy category",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Allergy name")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
            ],
            options={
                "verbose_name": "Allergy",
                "verbose_name_plural": "Allergies",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Medication name")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Vaccination name")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
            ],
            options={
                "verbose_name": "Vaccination",
                "verbose_name_plural": "Vaccinations",
            },
        ),
        migrations.AlterModelOptions(
            name="adopter",
            options={"verbose_name": "Adoptujący", "verbose_name_plural": "Adoptujący"},
        ),
        migrations.AlterModelOptions(
            name="animal",
            options={"verbose_name": "Zwierze", "verbose_name_plural": "Zwierzęta"},
        ),
        migrations.AlterModelOptions(
            name="healthcard",
            options={"verbose_name": "Karta zdrowia", "verbose_name_plural": "Karty zdrowia"},
        ),
        migrations.AlterModelOptions(
            name="temporaryhome",
            options={"verbose_name": "Dom tymczasowy", "verbose_name_plural": "Domy tymczasowe"},
        ),
        migrations.AlterModelOptions(
            name="veterinaryvisit",
            options={"verbose_name": "Wizyta weterynaryjna", "verbose_name_plural": "Wizyty weterynaryjne"},
        ),
        migrations.AlterField(
            model_name="adopter",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adres"),
        ),
        migrations.AlterField(
            model_name="adopter",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
        ),
        migrations.AlterField(
            model_name="adopter",
            name="owner",
            field=models.CharField(max_length=255, verbose_name="Imie i nazwisko właściciela"),
        ),
        migrations.AlterField(
            model_name="adopter",
            name="phone_number",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=9, message="Numer telefonu musi się składać z 9 cyfr"
                    )
                ],
                verbose_name="Numer telefonu",
            ),
        ),
        migrations.AlterField(
            model_name="adopter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_type",
            field=models.CharField(choices=[("DOG", "Pies"), ("CAT", "Kot")], max_length=255, verbose_name="Typ"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="birth_date",
            field=models.DateField(verbose_name="Data urodzenia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="date_when_found",
            field=models.DateField(verbose_name="Data znalezienia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="description_of_health",
            field=models.TextField(blank=True, verbose_name="Opis zdrowia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Samiec"), ("FEMALE", "Suczka")], max_length=50, verbose_name="Płeć"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="core.temporaryhome",
                verbose_name="Dom",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.ImageField(upload_to="animals/", verbose_name="Zdjęcie"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="location_where_found",
            field=models.CharField(max_length=255, verbose_name="Miejsce znalezienia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=2, message="Imie musi się składać z minimum 2 znaków"
                    )
                ],
                verbose_name="Nazwa",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="residence",
            field=models.CharField(
                choices=[("BASE", "Baza"), ("TEMPORARY_HOME", "Dom tymczasowy")],
                default="BASE",
                max_length=255,
                verbose_name="Miejsce przebywania",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("FOR_ADOPTION", "Do adopcji"),
                    ("ADOPTED", "Zaadoptowany"),
                    ("QUARANTINE", "Na kwarantannie"),
                    ("UNADOPTABLE", "Nieadoptowalny"),
                ],
                default="UNADOPTABLE",
                max_length=255,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Użytkownik",
            ),
        ),
        migrations.RemoveField(
            model_name="healthcard",
            name="allergies",
        ),
        migrations.AlterField(
            model_name="healthcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
        ),
        migrations.RemoveField(
            model_name="healthcard",
            name="drugs",
        ),
        migrations.AlterField(
            model_name="healthcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano"),
        ),
        migrations.RemoveField(
            model_name="healthcard",
            name="vaccinations",
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="apartment",
            field=models.CharField(blank=True, max_length=10, verbose_name="Numer mieszkania"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="building",
            field=models.CharField(max_length=20, verbose_name="Numer budynku"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="city",
            field=models.CharField(max_length=255, verbose_name="Miasto"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="owner",
            field=models.CharField(max_length=255, verbose_name="Imie i nazwisko właściciela"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="phone_number",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.MinLengthValidator(
                        limit_value=9, message="Numer telefonu musi się składać z 9 cyfr"
                    )
                ],
                verbose_name="Numer telefonu",
            ),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Ulica"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji"),
        ),
        migrations.AlterField(
            model_name="temporaryhome",
            name="zip_code",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=5, message="Kod pocztowy musi mieć 5 znaków")
                ],
                verbose_name="Kod pocztowy",
            ),
        ),
        migrations.AlterField(
            model_name="veterinaryvisit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Utworzono"),
        ),
        migrations.AlterField(
            model_name="veterinaryvisit",
            name="date",
            field=models.DateField(verbose_name="Data wizyty"),
        ),
        migrations.AlterField(
            model_name="veterinaryvisit",
            name="description",
            field=models.TextField(verbose_name="Opis wizyty"),
        ),
        migrations.AlterField(
            model_name="veterinaryvisit",
            name="doctor",
            field=models.CharField(
                choices=[("PIOTR", "Piotr"), ("JOANNA", "Joanna"), ("ALEKSANDRA", "Aleksandra")],
                max_length=255,
                verbose_name="Lekarz",
            ),
        ),
        migrations.AlterField(
            model_name="veterinaryvisit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano"),
        ),
        migrations.CreateModel(
            name="HealthCardVaccination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("health_card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.healthcard")),
                ("vaccination", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.vaccination")),
            ],
        ),
        migrations.CreateModel(
            name="HealthCardMedication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("health_card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.healthcard")),
                ("medication", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.medication")),
            ],
        ),
        migrations.CreateModel(
            name="HealthCardAllergy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allergy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.allergy")),
                ("health_card", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.healthcard")),
            ],
        ),
        migrations.AddField(
            model_name="healthcard",
            name="allergies",
            field=models.ManyToManyField(
                blank=True, through="core.HealthCardAllergy", to="core.allergy", verbose_name="Allergies"
            ),
        ),
        migrations.AddField(
            model_name="healthcard",
            name="drugs",
            field=models.ManyToManyField(
                blank=True, through="core.HealthCardMedication", to="core.medication", verbose_name="Medications"
            ),
        ),
        migrations.AddField(
            model_name="healthcard",
            name="vaccinations",
            field=models.ManyToManyField(
                blank=True, through="core.HealthCardVaccination", to="core.vaccination", verbose_name="Vaccinations"
            ),
        ),
    ]
