# Generated by Django 4.2.6 on 2023-10-25 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_allergy_medication_vaccination_alter_adopter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcardvaccination",
            name="vaccination_date",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Vaccination date"),
            preserve_default=False,
        ),
    ]
