# Generated by Django 4.2.6 on 2023-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_healthcardvaccination_vaccination_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcardallergy",
            name="description",
            field=models.TextField(blank=True, max_length=255, verbose_name="Opis"),
        ),
        migrations.AddField(
            model_name="healthcardmedication",
            name="description",
            field=models.TextField(blank=True, max_length=255, verbose_name="Opis"),
        ),
        migrations.AddField(
            model_name="healthcardvaccination",
            name="description",
            field=models.TextField(blank=True, max_length=255, verbose_name="Opis"),
        ),
    ]
