# Generated by Django 4.2.6 on 2023-10-27 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_alter_healthcardallergy_allergy_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allergy",
            options={"verbose_name": "Alergia", "verbose_name_plural": "Alergie"},
        ),
        migrations.AlterModelOptions(
            name="healthcardallergy",
            options={"verbose_name": "Health card - Allergy", "verbose_name_plural": "Health card - Allergies"},
        ),
        migrations.AlterModelOptions(
            name="healthcardmedication",
            options={"verbose_name": "Health card - Medication", "verbose_name_plural": "Health card - Medications"},
        ),
        migrations.AlterModelOptions(
            name="healthcardvaccination",
            options={"verbose_name": "Health card - Vaccination", "verbose_name_plural": "Health card - Vaccinations"},
        ),
        migrations.AlterModelOptions(
            name="medication",
            options={"verbose_name": "Lek", "verbose_name_plural": "Leki"},
        ),
        migrations.AlterModelOptions(
            name="vaccination",
            options={"verbose_name": "Szczepionka", "verbose_name_plural": "Szczepionki"},
        ),
        migrations.RemoveField(
            model_name="animal",
            name="user",
        ),
        migrations.RemoveField(
            model_name="healthcard",
            name="drugs",
        ),
        migrations.AddField(
            model_name="animal",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added by",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthcard",
            name="medications",
            field=models.ManyToManyField(
                blank=True, through="core.HealthCardMedication", to="core.medication", verbose_name="Leki"
            ),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="category",
            field=models.CharField(
                choices=[("POKARM", "Pokarm"), ("KONTAKT", "Kontakt"), ("INHALACJA", "Inhalacja")],
                max_length=255,
                verbose_name="Kategoria alergii",
            ),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Alergen"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_type",
            field=models.CharField(choices=[("PIES", "Pies"), ("KOT", "Kot")], max_length=255, verbose_name="Typ"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="date_when_found",
            field=models.DateField(blank=True, null=True, verbose_name="Data znalezienia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("SAMIEC", "Samiec"), ("SAMICA", "Samica")], max_length=50, verbose_name="Płeć"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="animals/", verbose_name="Zdjęcie"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="location_where_found",
            field=models.CharField(blank=True, max_length=255, verbose_name="Miejsce znalezienia"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="residence",
            field=models.CharField(
                choices=[("SCHRONISKO", "Schronisko"), ("TYMCZASOWY_DOM", "Tymczasowy dom")],
                default="BASE",
                max_length=255,
                verbose_name="Miejsce przebywania",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DO_ADOPCJI", "Do adopcji"),
                    ("ZAADOPTOWANY", "Zaadoptowany"),
                    ("KWARANTANNA", "Kwarantanna"),
                    ("NIEADOPTOWALNY", "Nieadoptowalny"),
                ],
                default="UNADOPTABLE",
                max_length=255,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="healthcard",
            name="allergies",
            field=models.ManyToManyField(
                blank=True, through="core.HealthCardAllergy", to="core.allergy", verbose_name="Alergie"
            ),
        ),
        migrations.AlterField(
            model_name="healthcard",
            name="animal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="healthcards",
                to="core.animal",
                verbose_name="Zwierze",
            ),
        ),
        migrations.AlterField(
            model_name="healthcard",
            name="vaccinations",
            field=models.ManyToManyField(
                blank=True, through="core.HealthCardVaccination", to="core.vaccination", verbose_name="Szczepionki"
            ),
        ),
        migrations.AlterField(
            model_name="healthcardallergy",
            name="allergy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.allergy", verbose_name="Alergia"
            ),
        ),
        migrations.AlterField(
            model_name="healthcardmedication",
            name="medication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.medication", verbose_name="Lek"
            ),
        ),
        migrations.AlterField(
            model_name="healthcardvaccination",
            name="vaccination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.vaccination", verbose_name="Szczepionka"
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nazwa szczepionki"),
        ),
    ]
