# Generated by Django 4.2.6 on 2023-10-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_animal_residence_alter_animal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("DO_ADOPCJI", "Do adopcji"),
                    ("ZAADOPTOWANY", "Zaadoptowany"),
                    ("KWARANTANNA", "Kwarantanna"),
                    ("NIE_DO_ADOPCJI", "Nie do adopcji"),
                ],
                default="NIEADOPTOWALNY",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
