# Generated by Django 4.2.6 on 2023-11-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_healthcardallergy_health_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="adopted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animals",
                to="core.adopter",
                verbose_name="Adopted by",
            ),
        ),
    ]
