# Generated by Django 4.2.7 on 2023-11-08 18:22

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_animal_id_alter_healthcard_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234", length=28, max_length=28, prefix="", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="healthcard",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefg1234", length=28, max_length=28, prefix="", primary_key=True, serialize=False
            ),
        ),
    ]
