# Generated by Django 4.2.7 on 2023-11-08 18:32

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_adopter_id_alter_animal_id_alter_healthcard_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345", length=6, max_length=8, prefix="p_", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
