# Generated by Django 4.2.7 on 2023-11-08 18:38

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_animal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcard",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="12345", length=7, max_length=10, prefix="hc_", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
