# Generated by Django 4.2.7 on 2023-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_animal_breed_alter_animal_temporary_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="character",
            field=models.CharField(blank=True, max_length=255, verbose_name="Character"),
        ),
        migrations.AddField(
            model_name="animal",
            name="chip",
            field=models.BooleanField(default=False, verbose_name="Chip"),
        ),
        migrations.AddField(
            model_name="animal",
            name="dewormed",
            field=models.BooleanField(default=False, verbose_name="Dewormed"),
        ),
        migrations.AddField(
            model_name="animal",
            name="for_who",
            field=models.CharField(blank=True, max_length=255, verbose_name="For who"),
        ),
        migrations.AddField(
            model_name="animal",
            name="neutered",
            field=models.BooleanField(default=False, verbose_name="Neutered"),
        ),
        migrations.AddField(
            model_name="animal",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="animal",
            name="vaccinated",
            field=models.BooleanField(default=False, verbose_name="Vaccinated"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, max_length=255, verbose_name="Breed"),
        ),
    ]
