# Generated by Django 4.2.7 on 2024-01-17 19:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_animal_character_animal_chip_animal_dewormed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, max_length=255, verbose_name="Rasa"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="character",
            field=models.CharField(blank=True, max_length=255, verbose_name="Charakter"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="chip",
            field=models.BooleanField(default=False, verbose_name="Czip"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="dewormed",
            field=models.BooleanField(default=False, verbose_name="Odrobaczony"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="for_who",
            field=models.CharField(blank=True, max_length=255, verbose_name="Dla kogo"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="neutered",
            field=models.BooleanField(default=False, verbose_name="Wykastrowany"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, populate_from="get_name_without_polish_letters", unique=True
            ),
        ),
    ]
